/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javamail;
import javax.mail.*;
import javax.mail.internet. InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;
import javax.mail.Flags.Flag;
import javax.mail.search.FlagTerm;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.activation.*;

/**
 *
 * @author aliif
 */
public class GetMail extends javax.swing.JFrame {

    /**
     * Creates new form GetMail
     */
    public GetMail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableInbox = new javax.swing.JTable();
        buttonInbox = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Muhammad Aliif Nashrullah - Java Get Mail");
        setResizable(false);

        tableInbox.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Subyek", "Dari", "Pesan", "Waktu"
            }
        ));
        tableInbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableInboxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableInbox);

        buttonInbox.setText("Inbox");
        buttonInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInboxActionPerformed(evt);
            }
        });

        textAreaMessage.setColumns(20);
        textAreaMessage.setRows(5);
        jScrollPane2.setViewportView(textAreaMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(buttonInbox)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(buttonInbox)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getMail (String host, String storeType, String user, String password) { 
	DefaultTableModel mod = new DefaultTableModel();
	mod.addColumn("No");
	mod.addColumn("Subyek");
	mod.addColumn("Dari");
	mod.addColumn("Pesan");
	mod.addColumn("Waktu");
	try {
		Properties properties = new Properties();
		properties.put("mail.imap.host", host); 
		properties.put("mail.imap.port", "993");
		properties.put("mail.imap.starttls.enable", "true"); 
		properties.put("mail.imap.ssl.trust", host);
		
		Session emailSession = Session.getDefaultInstance(properties); 
		Store store = emailSession.getStore("imaps");

		store.connect(host, user, password);

		Folder inbox = store.getFolder ("Inbox"); 
		inbox.open(Folder.READ_WRITE);

		Message[] messages = inbox.search(new FlagTerm(new Flags (Flag.SEEN), false)); 
		int mLength = messages.length;
		if (mLength>50) mLength=50;
		
		for (int i = 0, n = mLength; i < n; i++) {
			Message message = messages[i]; 
			message.setFlag (Flag.SEEN, true); 
			mod.addRow(new Object[]{
				i+1, message.getSubject(),
				message.getFrom()[0], message.getContent().toString(), message.getSentDate()
			});
		}

		tableInbox.setModel(mod);
		inbox.close(false);
		store.close();
	} catch (NoSuchProviderException e) {
		e.printStackTrace();
	} catch (MessagingException e) {
		e.printStackTrace();
	} catch (Exception e) {
		e.printStackTrace();
	}
    }

    
    private void buttonInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInboxActionPerformed
        // TODO add your handling code here:
        String host = "imap.gmail.com";
	String mailStoreType = "imap";
	String username = "aliefn311@gmail.com"; //akun gmail anda
	String password = "plal xkam ozjh upvb"; //password
	getMail (host, mailStoreType, username, password);
    }//GEN-LAST:event_buttonInboxActionPerformed

    private void tableInboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableInboxMouseClicked
        // TODO add your handling code here:
        int row = tableInbox.getSelectedRow();
	textAreaMessage.setText("No : "+tableInbox.getModel().getValueAt(row, 0).toString() 
                +"\nDari : "+tableInbox.getModel().getValueAt (row, 2).toString() 
                +"\nSubyek : "+tableInbox.getModel().getValueAt(row, 1).toString() 
                +"\nIsi : "+tableInbox.getModel().getValueAt(row, 3).toString()
                +"\nWaktu: "+tableInbox.getModel().getValueAt(row, 4).toString());
    }//GEN-LAST:event_tableInboxMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetMail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInbox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableInbox;
    private javax.swing.JTextArea textAreaMessage;
    // End of variables declaration//GEN-END:variables
}
